### ISSUE TITLE
failing test verbose output

### ISSUE THREAD

**Issue by tonycoz** [bodo-hugo-barwich/Process#47] opened 2023-09-27 10:41 UTC
You've asked on the testers list for verbose test output, I've attached it here.
[test.txt](https://github.com/bodo-hugo-barwich/Process/files/12737629/test.txt)
[test.txt](https://github.com/bodo-hugo-barwich/Process/files/12737631/test.txt)
The first is with a non-system perl.
The second is with /usr/bin/perl

Both were run in the cpan shell after the tests failing, so the requested prerequisite modules are available.

**Comment by bodo-hugo-barwich** [comment] 2023-09-28 11:40
Thank you for your feedback, Tony

**Comment by bodo-hugo-barwich** [comment] 2023-10-07 09:00
Especially the "_Runner Script Usage_" test does not have the verbose output like the other ones. But the best guess is that the "_Runner Usage Message_" check is tailored to tightly on the output as seen in the development environment and that differences in spaces might make it fail

**Comment by bodo-hugo-barwich** [comment] 2023-11-18 12:00
Hi @tonycoz,

May I ask you to capture the new extended output of this test please. Since I continue being unable to reproduce this.

**Comment by tonycoz** [comment] 2023-12-16 01:25
Sorry, about the delay:
[test.txt](https://github.com/bodo-hugo-barwich/Process/files/13690959/test.txt)

It looks like the usage message from Getopt::Long::Descriptive isn't what your test expects, so it looks like you have a simple fix.

**Comment by bodo-hugo-barwich** [comment] 2023-12-31 05:22
This error could be fixed with Release `v2.1.10`
[`Process::SubProcess` Release `v2.1.10`](https://github.com/bodo-hugo-barwich/Process/releases/tag/v2.1.10)

Thank you very much for your collaboration @tonycoz

**Closed by bodo-hugo-barwich** 2023-12-31 05:22 UTC
Labels: testing
